# -*- coding: utf-8 -*-
"""cs21b2028_q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RbK6pd4AidVr0ffGAa1k4uMOS3ThEtrJ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

path='/content/drive/MyDrive/Colab Notebooks/CS21B2028/PR ML Lab/datasets/'
df=pd.read_csv(path+'iris.csv')

#Question 2(a)

# Display the first few rows of the dataset
print("First few rows of the dataset:")
print(df.head())

# Display basic information about the dataset
print("\nDataset information:")
print(df.info())

# Display statistical summary of numerical attributes
print("\nStatistical summary:")
print(df.describe())

# Check for missing values
print("\nMissing values:")
print(df.isnull().sum())

# Check unique classes in the 'Species' column
print("\nUnique classes in 'Species' column:")
print(df['Species'].unique())

#question 2(b)

# Calculate the correlation matrix
correlation_matrix=[]
correlation_matrix = df.corr()

# Display the correlation matrix
print("Correlation Matrix:")
print(correlation_matrix)

#question 2(c)

# Create a heatmap to visualize the correlation matrix
plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

# #Question 2(d)

# Positively Correlated Pairs:

# Petal Length and Petal Width: These attributes have a strong positive correlation (close to 1). This implies that as the length of the petal increases, the width tends to increase as well. This positive correlation makes sense biologically, as larger petals often tend to be wider too.
# Negatively Correlated Pairs:

# Sepal Width and Petal Length: These attributes have a noticeable negative correlation (around -0.37). This suggests that as the width of the sepal increases, the length of the petal tends to decrease. The biological interpretation could be that species with wider sepals might have smaller petals.
# Sepal Length and Sepal Width: These attributes also show a moderate negative correlation (around -0.37). This implies that as the length of the sepal increases, the width tends to decrease, and vice versa.
# It's important to note that while correlation provides insights into the relationships between attributes, it doesn't imply causation. The observations made above are based on statistical relationships and should be interpreted cautiously, considering the biological context of iris flower characteristics.

# In summary, the correlations observed in the Iris flower dataset provide insights into how certain attributes tend to vary together. These insights can be valuable for understanding the characteristics of different iris species and potentially guiding further botanical research.

# #Question 2(e)

# Based on the correlation analysis of the Iris flower dataset, we can draw the following insights regarding the attributes that might have a strong influence on the characteristics of iris flowers:

# 1. Petal Length and Petal Width:
#    These attributes are strongly positively correlated (close to 1). This suggests that an increase in petal length is likely to be associated with an increase in petal width, and vice versa. Therefore, the size of the petals (both length and width) seems to be closely related and could be an important factor in distinguishing different iris species.

# 2. Sepal Length and Petal Length:
#    There is a positive correlation between sepal length and petal length. Although the correlation is not as strong as that between petal length and width, it still suggests that as the sepal length increases, the petal length tends to increase as well. This could indicate that larger flowers tend to have both longer sepals and longer petals.

# 3. Sepal Length and Petal Width:
#    While not as strong as the correlation between petal length and width, there is still a positive correlation between sepal length and petal width. This implies that as the sepal length increases, the petal width tends to increase as well. Larger flowers might have both longer sepals and wider petals.

# 4. Sepal Width and Petal Length:
#    There is a noticeable negative correlation between sepal width and petal length. This suggests that species with wider sepals tend to have smaller petals, and species with narrower sepals tend to have larger petals.

# 5. Sepal Length and Sepal Width:
#    Sepal length and sepal width are negatively correlated. This indicates that as the sepal length increases, the sepal width tends to decrease, and vice versa. This could imply a trade-off between sepal length and width in the characteristics of different iris species.

# Overall, petal length, petal width, sepal length, and sepal width seem to be the attributes that have a strong influence on the characteristics of iris flowers. The correlations observed provide insights into how these attributes tend to vary together and potentially contribute to the differentiation of iris species. However, it's important to remember that correlation does not imply causation, and further research would be needed to establish any causal relationships between these attributes and iris flower characteristics.